Repository dogechain-lab/dogechain, pull requests merged in 2022-04, with the labels that each got.

#9 WIP: New pre-deploy contracts
  command/common.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/ibft/switch/ibft_switch.go
  command/ibft/switch/params.go
  command/ibft/switch/result.go
  consensus/ibft/hooks.go
  consensus/ibft/pos.go
  contracts/abis/abis.go
  contracts/abis/json.go
  contracts/bridge/events.go
  contracts/systemcontracts/system_contracts.go
  contracts/validatorset/query.go
  contracts/validatorset/query_test.go
  e2e/framework/config.go
  e2e/framework/helper.go
  e2e/framework/testserver.go
  e2e/pos_poa_switch_test.go
  e2e/pos_test.go
  helper/bridge/bridge.go
  helper/staking/staking.go
  helper/validatorset/validatorset.go
  helper/vault/vault.go
  state/executor.go
Labels: feature, investigating

#10 Fix ibft not mining bug when network split on waiting for commit mess…
  consensus/ibft/ibft.go
  contracts/abis/abis.go
  e2e/framework/config.go
Labels: hotfix

#17 Use proposer address as miner when building block
  consensus/ibft/ibft.go
Labels: feature

#14 Fix/remove filter after connection closed
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/filter_manager.go
  jsonrpc/filter_manager_test.go
  jsonrpc/query.go
  jsonrpc/query_test.go
Labels: bug fix

#18 daemon for jury
  command/server/params.go
  command/server/server.go
  go.mod
  go.sum
  helper/daemon/attr_default.go
  helper/daemon/attr_windows.go
  helper/daemon/daemon.go
  secrets/local/local.go
  secrets/secrets.go
  server/config.go
  server/server.go
Labels: feature

#19 Upgrade system contracts ABI and bytecodes
  contracts/abis/json.go
  helper/bridge/bridge.go
  helper/validatorset/validatorset.go
  helper/vault/vault.go
Labels: feature

#23 ethpoint GasPrice() return default 50 Gwei.
  jsonrpc/eth_endpoint.go
Labels: feature

#24 Remove assets of init ValidatorSet
  helper/validatorset/validatorset.go
Labels: hotfix

#25 Upgrade system contracts ABI and bytecodes
  contracts/abis/json.go
  helper/bridge/bridge.go
  helper/validatorset/validatorset.go
  helper/vault/vault.go
Labels: feature, bug fix
