Repository dogechain-lab/dogechain, pull requests merged in 2022-12, with the labels that each got.

#265 Feat faster bulk syncing
  archive/restore.go
  archive/restore_test.go
  blockchain/blockchain.go
  command/helper/helper.go
  command/server/config.go
  command/server/params.go
  command/server/server.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/ibft/consensus.go
  consensus/ibft/currentstate/state.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  consensus/ibft/msg_queue.go
  helper/progress/chain.go
  jsonrpc/dispatcher_test.go
  jsonrpc/filter_manager.go
  network/dial/dial_queue_test.go
  network/e2e_testing.go
  network/gossip.go
  network/gossip_test.go
  network/server.go
  network/server_discovery.go
  protocol/blockchain.go
  protocol/client.go
  protocol/client_test.go
  protocol/interface.go
  protocol/peer.go
  protocol/peer_test.go
  protocol/proto/v1.pb.go
  protocol/proto/v1.proto
  protocol/proto/v1_grpc.pb.go
  protocol/service.go
  protocol/service_test.go
  protocol/service_v1.go
  protocol/skeleton.go
  protocol/status.go
  protocol/sync_peer.go
  protocol/syncer.go
  protocol/syncer_test.go
  protocol/testing.go
  server/config.go
  server/server.go
  txpool/event_manager_test.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature, breaking change

#271 [syncer] Forgetting non-Dogechain protocol peer
  archive/restore.go
  helper/progress/chain.go
  jsonrpc/eth_endpoint.go
  jsonrpc/types.go
  network/server.go
  protocol/client.go
  protocol/client_test.go
  protocol/interface.go
  protocol/peer.go
  protocol/syncer.go
  protocol/syncer_test.go
Labels: feature, bug fix

#274 [command] reverify subcommand, reverify storage block data
  blockchain/blockchain.go
  command/reverify/params.go
  command/reverify/reverify.go
  command/root/root.go
  consensus/consensus.go
  consensus/ibft/ibft.go
  e2e/reverify_test.go
  helper/kvdb/kvdb.go
  helper/kvdb/leveldb.go
  helper/kvdb/leveldb_test.go
  network/e2e_testing.go
  network/gossip.go
  network/gossip_test.go
  network/interface.go
  network/server.go
  network/server_discovery.go
  network/server_identity.go
  network/server_nonnetwork.go
  network/server_test.go
  protocol/client.go
  protocol/client_test.go
  protocol/interface.go
  protocol/service.go
  protocol/syncer.go
  protocol/syncer_test.go
  reverify/chain.go
  reverify/reverify.go
  server/builtin.go
  server/server.go
  txpool/txpool.go
Labels: feature

#261 [discover] Filtering peers using CIDR ranges
  command/common.go
  command/server/config.go
  command/server/params.go
  command/server/server.go
  network/common/common.go
  network/common/common_test.go
  network/config.go
  network/discovery/discovery.go
  network/discovery/discovery_test.go
  network/server_discovery.go
Labels: feature

#258 [Feature] merge state update to single transaction
  blockchain/blockchain.go
  blockchain/testing.go
  command/server/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  consensus/dev/dev.go
  consensus/ibft/ibft.go
  go.mod
  go.sum
  reverify/chain.go
  reverify/reverify.go
  server/config.go
  server/server.go
  server/server_metrics.go
  state/executor.go
  state/immutable-trie/hasher.go
  state/immutable-trie/metrics.go
  state/immutable-trie/node.go
  state/immutable-trie/state.go
  state/immutable-trie/statedb.go
  state/immutable-trie/statedb_test.go
  state/immutable-trie/statedb_transaction.go
  state/immutable-trie/storage.go
  state/immutable-trie/trie.go
  state/immutable-trie/txn.go
  state/state.go
  state/testing.go
  state/transition_test.go
  state/txn_test.go
  tests/evm_test.go
  tests/state_test.go
  tests/testing.go
  types/buildroot/buildroot.go
Labels: feature, bug fix
