Repository dogechain-lab/dogechain, pull requests merged in 2022-11, with the labels that each got.

#237 [network] Check peerid, block self connect self
  network/identity/identity.go
  network/identity/identity_test.go
Labels: bug fix

#238 [ibft] Banish transactions due to abnormal long time execution
  command/genesis/params.go
  consensus/ibft/hooks.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  state/executor.go
Labels: hotfix

#244 Fix ibft test crash after using hardfork compatible signer
  consensus/ibft/ibft_test.go
Labels: bug fix

#242 [txpool] remove read lock, fix dead lock
  helper/concurrentmap/concurrent_map.go
  helper/concurrentmap/concurrent_map_test.go
  protocol/syncer.go
  protocol/syncer_test.go
  txpool/account.go
Labels: bug fix

#248 Fix transaction index shadowed when querying transaction receipt
  jsonrpc/eth_endpoint.go
Labels: bug fix

#239 [sycner] Remove different network peer
  network/server.go
  network/server_discovery.go
  network/server_identity.go
  protocol/syncer.go
Labels: feature, bug fix

#249 [db] Tuning leveldb options to better performance
  blockchain/testing.go
  consensus/ibft/snapshot.go
  helper/kvdb/builder.go
  server/server.go
  server/server_metrics.go
  state/immutable-trie/metrics.go
  state/immutable-trie/state.go
  state/immutable-trie/state_test.go
  state/immutable-trie/trie.go
  state/txn.go
  tests/testing.go
Labels: bug fix

#250 [ibft] Fix build block write system transactions failed due to gas limit reach
  blockchain/blockchain.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  contracts/validatorset/query.go
  contracts/validatorset/query_test.go
  state/executor.go
Labels: bug fix

#251 [ibft] merge back patch 1.1.3
  command/genesis/params.go
  consensus/ibft/hooks.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  state/executor.go
Labels: bug fix

#253 Update detroit hard fork block height on mainnet
  mainnet-genesis.json
Labels: feature, breaking change

#254 [txpool] Long time consuming ddos attack protection
  chain/params.go
  consensus/ibft/hooks.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  server/server.go
  txpool/txpool.go
Labels: hotfix

#256 [server] Fix server close blocking
  blockchain/blockchain.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  e2e/backup_test.go
  network/server.go
  server/server.go
  txpool/txpool.go
Labels: bug fix

#257 [ibft] Fix ddos mark count increase insanely with only one transaction
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  protocol/syncer.go
Labels: bug fix

#260 [ibft] Fix block extraData not canonical sealed
  blockchain/blockchain.go
  consensus/ibft/currentstate/state.go
  consensus/ibft/header_hash_test.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  consensus/ibft/msg_queue.go
  consensus/ibft/proto/ibft.pb.go
  consensus/ibft/proto/ibft.proto
  consensus/ibft/proto/ibft_grpc.pb.go
  consensus/ibft/proto/operator.pb.go
  consensus/ibft/proto/operator_grpc.pb.go
  consensus/ibft/sign.go
  consensus/ibft/validator/validators.go
  e2e/syncer_test.go
  types/address.go
  types/hash.go
  types/util.go
Labels: feature, bug fix

#263 [ibft] Banish ddos contract without release
  blockchain/blockchain.go
  blockchain/metrics.go
  chain/params.go
  consensus/ibft/ibft.go
  server/server.go
  txpool/txpool.go
Labels: hotfix

#200 Fix: routing table size use MaxPeers config
  helper/common/common.go
  network/server_discovery.go
Labels: bug fix

#264 [prometheus] fix metric name
  blockchain/metrics.go
Labels: bug fix
