Repository dogechain-lab/dogechain, pull requests merged in 2022-05, with the labels that each got.

#30 Update snapshot after processBlock ends
  blockchain/blockchain.go
  blockchain/testing.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/ibft.go
Labels: bug fix

#29 Fix issue can't fetch genesis block by hash
  blockchain/blockchain.go
Labels: bug fix

#35 fix auditing v-doge-vul-002
  consensus/ibft/ibft.go
Labels: bug

#36 [TxPool] Self pruning stuck transactions
  command/default.go
  command/server/config.go
  command/server/params.go
  command/server/server.go
  server/config.go
  server/server.go
  txpool/account.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#37 Fix eth_gasPrice test failure
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
Labels: bug fix

#38 Fix v-doge-vul-004
  protocol/service_v1.go
  protocol/syncer.go
  protocol/syncer_test.go
Labels: hotfix

#41 Fix V-DOGE-VUL-008
  consensus/ibft/sign_test.go
  crypto/crypto.go
Labels: hotfix

#42 Fix V-DOGE-VUL-011 & V-DOGE-VUL-012
  consensus/ibft/ibft.go
Labels: hotfix

#40 Fix V-DOGE-VUL-007
  txpool/txpool.go
  txpool/txpool_test.go
Labels: hotfix

#47 fix v-doge-vul-009
  consensus/ibft/ibft.go
Labels: bug fix

#52 Reorder the db WriteBlock codes to reduce the harm of partial-write
  blockchain/blockchain.go
Labels: hotfix

#53 Add server command log-to flag
  command/server/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  server/config.go
  server/server.go
Labels: feature

#54 [TxPool] Fix ErrAlreadyUnknown in tests
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#58 Fix V-DOGE-VUL-016
  archive/types.go
  blockchain/storage/keyvalue.go
  blockchain/storage/utils.go
  consensus/ibft/extra.go
  consensus/ibft/header_hash.go
  consensus/ibft/sign.go
  crypto/crypto.go
  crypto/txsigner.go
  go.mod
  go.sum
  helper/keccak/keccak.go
  helper/keccak/pool.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_state_test.go
  state/immutable-trie/hasher.go
  state/immutable-trie/storage.go
  state/immutable-trie/trie.go
  state/state.go
  state/txn_test.go
  tests/evm_test.go
  types/buildroot/buildroot.go
  types/header_hash.go
  types/rlp_marshal.go
  types/rlp_marshal_storage.go
  types/rlp_unmarshal.go
  types/rlp_unmarshal_storage.go
Labels: bug fix

#60 Remove contractAddress from receipt if not contract deployment
  archive/restore_test.go
  archive/types.go
  blockchain/storage/testing.go
  consensus/ibft/extra.go
  jsonrpc/types.go
  state/executor.go
  state/state.go
  types/receipt.go
  types/rlp_encoding_test.go
  types/rlp_marshal_storage.go
  types/rlp_unmarshal.go
  types/rlp_unmarshal_storage.go
  types/types.go
Labels: hotfix, breaking change

#63 reverse vault api v1.5.0 back to v1.3.1
  go.mod
  go.sum
Labels: bug fix

#64 Fix crash when timeout filter happen to be nil
  jsonrpc/filter_manager.go
Labels: hotfix

#65 Use block-gas-target flag in building block
  command/server/params.go
Labels: bug fix

#69 sycner broadcast synchronous to asynchronous
  protocol/syncer.go
Labels: bug fix
