Repository dogechain-lab/dogechain, pull requests merged in 2022-09, with the labels that each got.

#154 Resolve memory creep when copy header
  .github/workflows/main.yml
  Makefile
  lint-rule.yaml
  state/runtime/precompiled/base.go
  types/header.go
Labels: bug fix

#153 [Txpool] Prune inactive account enqueued transactions when promotion outdated
  command/default.go
  command/server/config.go
  command/server/server.go
  txpool/account.go
  txpool/default.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#119 [txpool] Replace same nonce with better price transaction
  command/txpool/subscribe/params.go
  command/txpool/subscribe/txpool_subscribe.go
  txpool/account.go
  txpool/proto/operator.pb.go
  txpool/proto/operator.proto
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature

#152 Add enable-ws flag in server command
  command/server/config.go
  command/server/params.go
  command/server/server.go
  e2e/framework/config.go
  e2e/framework/testserver.go
  e2e/websocket_test.go
  jsonrpc/jsonrpc.go
  server/config.go
  server/server.go
Labels: feature

#161 Feature: NAT use different port
  command/server/init.go
  command/server/params.go
  command/server/server.go
  network/config.go
  network/server.go
  network/server_test.go
Labels: feature

#168 [HardFork] portland hardfork on fixing bridge withdrawn issue
  blockchain/blockchain.go
  chain/params.go
  consensus/dev/dev.go
  consensus/ibft/ibft.go
  contracts/abis/json.go
  contracts/bridge/events.go
  contracts/upgrader/upgrader.go
  server/server.go
  state/executor.go
  txpool/txpool.go
Labels: hotfix

#169 [Txpool] Demote all pending transactions when nonce not right in building block
  command/server/config.go
  command/server/params.go
  command/server/server.go
  command/txpool/status/result.go
  command/txpool/status/txpool_status.go
  consensus/dev/dev.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  server/config.go
  server/server.go
  state/executor.go
  txpool/account.go
  txpool/default.go
  txpool/operator.go
  txpool/proto/operator.pb.go
  txpool/proto/operator.proto
  txpool/proto/v1.pb.go
  txpool/queue.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/transaction.go
Labels: bug fix

#170 Respect gas limit config in eth_gasPrice endpoint
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/web3_endpoint_test.go
  server/server.go
Labels: feature

#162 Backup support zstd
  archive/backup.go
  archive/backup_test.go
  archive/restore.go
  command/backup/backup.go
  command/backup/params.go
  command/helper/helper.go
  command/loadbot/generators.go
  e2e/backup_test.go
  e2e/framework/config.go
  e2e/framework/testserver.go
  go.mod
  go.sum
  helper/common/common.go
  network/grpc/grpc.go
  server/server.go
Labels: feature

#177 Makefile add test command
  .gitignore
  Makefile
Labels: feature

#173 update goreleaser, remove unused step
  .github/workflows/release.yml
Labels: feature

#172 Package mainnet genesis.json
  .goreleaser.yml
  mainnet-genesis.json
Labels: feature

#181 replace time.After to time.NewTimer
  blockchain/subscription_test.go
  command/helper/helper.go
  consensus/dev/dev.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  jsonrpc/dispatcher_test.go
  network/dial/dial_queue_test.go
  network/gossip_test.go
  network/server.go
  protocol/sync_peer.go
  protocol/testing.go
  txpool/event_manager_test.go
Labels: bug fix

#178 replace sync.Map
  command/loadbot/duration.go
  command/loadbot/execution.go
  helper/concurrentmap/concurrent_map.go
  helper/concurrentmap/concurrent_map_test.go
  network/identity/identity.go
  network/identity/identity_test.go
  network/server.go
  protocol/syncer.go
  protocol/testing.go
  txpool/account.go
  txpool/queue.go
  txpool/txpool.go
Labels: bug fix

#192 Fix: e2e defunct process
  Makefile
  e2e/framework/cmd.go
  e2e/framework/cmd_unix.go
  e2e/framework/cmd_windows.go
  e2e/framework/helper.go
  e2e/framework/testserver.go
  jsonrpc/mocks_test.go
  protocol/testing.go
Labels: bug fix

#191 Stop server elegantly instead of panic when db closed
  blockchain/blockchain.go
  blockchain/testing.go
  e2e/framework/config.go
  e2e/framework/helper.go
  e2e/framework/ibft.go
  e2e/framework/testserver.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  network/server.go
  server/server.go
  state/executor.go
  state/immutable-trie/storage.go
  state/runtime/runtime.go
  state/txn.go
  txpool/txpool.go
Labels: bug fix

#194 [Memory leak] Remove dangling pointers in the blockchain subscription
  blockchain/subscription.go
  blockchain/subscription_test.go
Labels: hotfix

#196 [Cmd] Set server command seal flag default to false
  command/server/server.go
  txpool/txpool.go
Labels: bug fix

#193 Refactoring leveldb code
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/storage/errors.go
  blockchain/storage/kvstorage/kvstorage.go
  blockchain/storage/kvstorage/leveldb.go
  blockchain/storage/kvstorage/leveldb_test.go
  blockchain/storage/kvstorage/memory.go
  blockchain/storage/kvstorage/memory_test.go
  blockchain/storage/leveldb/builder.go
  blockchain/storage/leveldb/leveldb.go
  blockchain/storage/leveldb/leveldb_test.go
  blockchain/storage/storage.go
  blockchain/testing.go
  command/server/server.go
  helper/kvdb/builder.go
  helper/kvdb/kvdb.go
  helper/kvdb/leveldb.go
  server/server.go
  state/immutable-trie/hasher.go
  state/immutable-trie/state.go
  state/immutable-trie/storage.go
  state/immutable-trie/trie.go
Labels: feature
