Repository dogechain-lab/dogechain, pull requests merged in 2022-10, with the labels that each got.

#202 [jsonrpc] Add debug_traceTransaction endpoint
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/dispatcher.go
  jsonrpc/eth_endpoint.go
  server/server.go
  state/executor.go
  state/runtime/dummy_logger.go
  state/runtime/evm/evm.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/opcodes.go
  state/runtime/evm/state.go
  state/runtime/logger.go
  state/runtime/runtime.go
  state/tracer/structlogger/logger.go
  state/tracer/tracer.go
Labels: feature

#208 Fix evm state test crash when not providing host
  state/executor.go
  state/runtime/evm/state.go
  state/runtime/evm/state_test.go
Labels: bug fix

#205 Feature: add prometheus metrics
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/metrics.go
  blockchain/testing.go
  jsonrpc/jsonrpc.go
  jsonrpc/metrics.go
  server/server.go
  server/server_metrics.go
Labels: feature

#203 Fix: gossip topic subscribe backpressure
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  go.mod
  network/gossip.go
  network/gossip_test.go
  txpool/txpool.go
Labels: bug fix

#214 [network] Fix bootnode re-discovery issue(Upstream PR 0xPolygon#775)
  network/discovery/discovery.go
  network/server.go
  network/server_discovery.go
  network/testing/testing.go
Labels: bug fix

#210 [network] increase pubsub message buffers
  network/gossip.go
  network/server.go
Labels: bug fix

#218 [jsonrpc] New server option for fine-grained control over endpoint namespaces
  command/server/config.go
  command/server/params.go
  command/server/server.go
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/web3_endpoint_test.go
  server/config.go
  server/server.go
Labels: feature

#217 [HardFork] Deposit block reward to validator after detroit hard fork
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/storage/testing.go
  blockchain/testing.go
  chain/params.go
  consensus/consensus.go
  consensus/dev/dev.go
  consensus/dummy/dummy.go
  consensus/ibft/currentstate/state.go
  consensus/ibft/currentstate/state_test.go
  consensus/ibft/ibft.go
  consensus/ibft/ibft_test.go
  consensus/ibft/msg_queue.go
  consensus/ibft/msg_queue_test.go
  consensus/ibft/pos.go
  consensus/ibft/snapshot.go
  consensus/ibft/snapshot_test.go
  consensus/ibft/state.go
  consensus/ibft/state_test.go
  consensus/ibft/timeout.go
  consensus/ibft/timeout_test.go
  consensus/ibft/validator/validators.go
  contracts/abis/encode.go
  contracts/abis/json.go
  contracts/upgrader/upgrader.go
  contracts/validatorset/query.go
  contracts/validatorset/query_test.go
  e2e/framework/helper.go
  graphql/graphql.go
  jsonrpc/debug_endpoint.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/eth_txpool_test.go
  jsonrpc/filter_manager.go
  jsonrpc/txpool_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  jsonrpc/types.go
  jsonrpc/types_test.go
  mainnet-genesis.json
  server/server.go
  state/executor.go
  state/runtime/evm/state.go
  txpool/lookup_map.go
  txpool/operator.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/rlp_encoding_test.go
  types/rlp_unmarshal.go
  types/transaction.go
Labels: feature, breaking change

#223 [hardfork] Create a devnet only pre-portland hard fork
  chain/params.go
  contracts/upgrader/upgrader.go
Labels: bug fix

#220 Make the header timestamp respect time of generation
  consensus/ibft/ibft.go
Labels: bug fix

#228 Fix disable default debug vars
  command/helper/helper.go
  command/server/config.go
  command/server/params.go
  command/server/server.go
  graphql/service.go
  jsonrpc/jsonrpc.go
  server/config.go
  server/server.go
Labels: bug fix

#226 Create state abstraction boundaries for write-ops in the state transition
  state/executor.go
  state/testing.go
  state/txn.go
  tests/state_test.go
  tests/testing.go
Labels: feature

#229 Add support for better client version details
  .github/workflows/build.yml
  Makefile
  command/version/result.go
  command/version/version.go
  jsonrpc/dispatcher.go
  jsonrpc/jsonrpc.go
  jsonrpc/jsonrpc_test.go
  jsonrpc/web3_endpoint.go
  jsonrpc/web3_endpoint_test.go
  versioning/versioning.go
Labels: bug fix

#227 Fix the size of return value by eth_getStorageAt
  jsonrpc/eth_endpoint.go
Labels: bug fix

#219 [leveldb] default parameter change
  helper/kvdb/builder.go
  server/server.go
Labels: bug fix

#215 [state] cache optimization
  blockchain/testing.go
  server/server.go
  server/server_metrics.go
  state/immutable-trie/metrics.go
  state/immutable-trie/state.go
  state/immutable-trie/state_test.go
  state/immutable-trie/trie.go
  state/txn.go
  tests/testing.go
Labels: feature

#216 [leveldb] set DisableSeeksCompaction to true
  helper/kvdb/builder.go
Labels: bug fix

#232 Use header gas limit when querying validators in pos
  consensus/ibft/pos.go
  contracts/validatorset/query.go
  contracts/validatorset/query_test.go
Labels: bug fix

#231 [ibft] Ignore ibft message when node is not a validator
  consensus/ibft/ibft.go
Labels: bug fix
