Repository dogechain-lab/dogechain, pull requests merged in 2023-03, with the labels that each got.

#312 [CI] Update GitHub actions config
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .goreleaser.yml
  Dockerfile.release
  Makefile
Labels: bug fix

#309 [syncer] fix syncer block
  e2e/ibft_test.go
  helper/common/rand.go
  protocol/peer.go
  protocol/peer_test.go
  protocol/syncer.go
  protocol/syncer_test.go
Labels: bug fix

#314 [txpool] fix channel close
  txpool/txpool.go
Labels: bug fix

#315 [CI] Merge job, add job dependencies
  .github/workflows/actions.yml
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
Labels: bug fix

#305 [network] Improved Connection Manager
  blockchain/blockchain.go
  e2e/backup_test.go
  e2e/const.go
  e2e/encoding_test.go
  e2e/framework/helper.go
  e2e/genesis_test.go
  e2e/ibft_test.go
  e2e/logs_test.go
  e2e/reverify_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  e2e/websocket_test.go
  helper/common/common.go
  network/bootnodes.go
  network/client/discovery.go
  network/client/identity.go
  network/client/interface.go
  network/client/syncerV1.go
  network/discovery/discovery.go
  network/discovery/discovery_test.go
  network/discovery_e2e_test.go
  network/e2e_testing.go
  network/gossip.go
  network/identity/identity.go
  network/identity/identity_test.go
  network/interface.go
  network/keep_available.go
  network/server.go
  network/server_discovery.go
  network/server_identity.go
  network/server_nonnetwork.go
  network/server_test.go
  network/testing/testing.go
  protocol/client.go
  protocol/client_test.go
  txpool/event_subscription.go
  txpool/event_subscription_test.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug fix

#319 [syncer] fix syncer timeout
  protocol/client.go
  protocol/syncer.go
Labels: bug fix

#328 Register missing txpool metrics
  txpool/metrics.go
Labels: hotfix

#330 [txpool] Add destructive contract list
  chain/params.go
  server/server.go
  txpool/ddos.go
  txpool/txpool.go
Labels: feature

#317 [feature] support jaeger telemetry
  command/default.go
  command/helper/helper.go
  command/server/config.go
  command/server/params.go
  command/server/server.go
  go.mod
  go.sum
  helper/common/common.go
  helper/common/common_test.go
  helper/telemetry/interface.go
  helper/telemetry/jaeger.go
  helper/telemetry/nil_provider.go
  helper/telemetry/type_convert.go
  jsonrpc/jsonrpc.go
  network/discovery/discovery.go
  network/e2e_testing.go
  network/event/peer_event.go
  network/grpc/grpc.go
  network/identity/identity.go
  network/keep_available.go
  network/peer_connect.go
  network/server.go
  network/server_discovery.go
  network/server_identity.go
  network/server_test.go
  network/testing/testing.go
  protocol/client_test.go
  protocol/service.go
  server/config.go
  server/server.go
Labels: feature

#333 [jsonrpc] Use gas price oracle suggest tip instead of constant value
  blockchain/blockchain.go
  command/server/config.go
  command/server/init.go
  command/server/params.go
  command/server/server.go
  graphql/graphql.go
  graphql/service.go
  helper/gasprice/gasprice.go
  jsonrpc/eth_endpoint.go
  server/config.go
  server/jsonrpc_store.go
  server/server.go
Labels: bug fix

#335 [blockchain] Update current block avg and max gas price metrics
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/metrics.go
  blockchain/testing.go
Labels: bug fix
