Repository dogechain-lab/dogechain, pull requests merged in 2023-01, with the labels that each got.

#276 [JSON-RPC] add API call metrics
  blockchain/blockchain.go
  jsonrpc/debug_endpoint.go
  jsonrpc/dispatcher.go
  jsonrpc/dispatcher_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/metrics.go
  jsonrpc/net_endpoint.go
  jsonrpc/txpool_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  jsonrpc/web3_endpoint.go
  jsonrpc/web3_endpoint_test.go
  network/identity_e2e_test.go
  network/interface.go
  network/server.go
  network/server_nonnetwork.go
  network/server_test.go
  server/jsonrpc_store.go
  server/jsonrpc_store_metrics.go
  server/server.go
  server/server_metrics.go
Labels: feature

#278 [network] fix workqueue close
  network/gossip.go
Labels: bug fix

#279 [crypto] Keccak256 method add sync.Pool
  crypto/crypto.go
  state/immutable-trie/trie.go
  state/txn.go
Labels: bug fix

#277 [state] pre-allocate Node struct
  state/immutable-trie/node.go
  state/immutable-trie/nodepool.go
  state/immutable-trie/nodepool_test.go
  state/immutable-trie/statedb.go
  state/immutable-trie/statedb_transaction.go
  state/immutable-trie/storage.go
  state/immutable-trie/trie.go
Labels: feature

#283 [protocol] Move close channel after close topics
  consensus/ibft/ibft.go
  protocol/client.go
  protocol/client_test.go
  txpool/txpool.go
Labels: bug fix

#282 [metrics] remove go-kit dependencies
  blockchain/blockchain.go
  blockchain/metrics.go
  consensus/ibft/consensus.go
  consensus/ibft/ibft.go
  consensus/metrics.go
  go.mod
  go.sum
  helper/metrics/metrics.go
  jsonrpc/jsonrpc.go
  jsonrpc/metrics.go
  network/metrics.go
  network/server.go
  network/server_identity.go
  server/jsonrpc_store_metrics.go
  state/immutable-trie/metrics.go
  state/immutable-trie/statedb_transaction.go
  state/immutable-trie/trie.go
  txpool/metrics.go
  txpool/txpool.go
Labels: bug fix

#286 [Fix] fix judgment logic
  helper/metrics/metrics.go
Labels: hotfix

#280 [network] Feature: support static node
  chain/chain.go
  command/common.go
  command/genesis/genesis.go
  command/genesis/params.go
  command/peers/add/params.go
  command/peers/add/peers_add.go
  e2e/broadcast_test.go
  e2e/discovery_test.go
  e2e/framework/config.go
  e2e/framework/helper.go
  e2e/framework/ibft.go
  e2e/framework/testserver.go
  e2e/ibft_test.go
  e2e/syncer_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  network/discovery_e2e_test.go
  network/e2e_testing.go
  network/identity_e2e_test.go
  network/interface.go
  network/server.go
  network/server_discovery.go
  network/server_nonnetwork.go
  network/server_test.go
  network/staticnodes.go
  protocol/client_test.go
  server/proto/system.pb.go
  server/proto/system.proto
  server/proto/system_grpc.pb.go
  server/server.go
  server/system_service.go
Labels: feature

#287 Feat whitelist for normal usage contracts
  command/txpool/addwhite/params.go
  command/txpool/addwhite/result.go
  command/txpool/addwhite/txpool_addwhite.go
  command/txpool/ddoslist/params.go
  command/txpool/ddoslist/result.go
  command/txpool/ddoslist/txpool_delwhite.go
  command/txpool/delwhite/params.go
  command/txpool/delwhite/result.go
  command/txpool/delwhite/txpool_delwhite.go
  command/txpool/txpool.go
  consensus/ibft/ibft_test.go
  jsonrpc/txpool_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  server/jsonrpc_store.go
  server/proto/system.pb.go
  server/proto/system.proto
  server/proto/system_grpc.pb.go
  server/system_service.go
  txpool/ddos.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: feature, bug fix
