Repository dogechain-lab/dogechain, pull requests merged in 2023-02, with the labels that each got.

#296 Add read abstraction to the State
  graphql/endpoints.go
  graphql/graphql.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_state_test.go
  server/jsonrpc_store.go
  server/server.go
  state/executor.go
  state/immutable-trie/hasher.go
  state/immutable-trie/node.go
  state/immutable-trie/snapshot.go
  state/immutable-trie/statedb.go
  state/immutable-trie/statedb_test.go
  state/immutable-trie/statedb_transaction.go
  state/immutable-trie/trie.go
  state/immutable-trie/txn.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/state.go
  state/runtime/logger.go
  state/runtime/runtime.go
  state/state.go
  state/testing.go
  state/tracer/structlogger/logger.go
  state/txn.go
  state/txn_test.go
  tests/evm_test.go
  tests/testing.go
  types/buildroot/buildroot.go
Labels: feature, bug fix

#180 Upgrade libp2p v0.22.0
  command/loadbot/execution.go
  command/secrets/init/params.go
  command/status/status.go
  consensus/ibft/ibft.go
  e2e/framework/testserver.go
  e2e/genesis_test.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  go.mod
  go.sum
  helper/tests/testing.go
  network/bootnodes.go
  network/common/common.go
  network/connections.go
  network/dial/dial_queue.go
  network/dial/dial_queue_test.go
  network/dial/dial_task.go
  network/discovery/discovery.go
  network/discovery/discovery_test.go
  network/e2e_testing.go
  network/event/peer_event.go
  network/gossip.go
  network/gossip_test.go
  network/grpc/grpc.go
  network/identity/identity.go
  network/identity/identity_test.go
  network/interface.go
  network/keystore.go
  network/proto/discovery.pb.go
  network/proto/discovery_grpc.pb.go
  network/server.go
  network/server_discovery.go
  network/server_identity.go
  network/server_nonnetwork.go
  network/server_test.go
  network/staticnodes.go
  network/testing/testing.go
  protocol/client.go
  protocol/client_test.go
  protocol/interface.go
  protocol/peer.go
  protocol/peer_test.go
  protocol/service.go
  protocol/syncer.go
  protocol/syncer_test.go
  secrets/helper/helper.go
  secrets/local/local_test.go
  server/system_service.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: dependencies

#298 [test] fix unit test
  protocol/client_test.go
Labels: bug fix

#297 [backup] Improved writing and reading of blockchain backup file
  archive/backup.go
  archive/backup_test.go
  archive/restore.go
  archive/restore_test.go
  command/backup/params.go
  server/server.go
Labels: feature, bug fix

#306 [dependency] update golang sub-repositories
  go.mod
  go.sum
Labels: bug fix

#307 [dependency] update third-party packages
  go.mod
  go.sum
  secrets/awsssm/aws_ssm.go
Labels: bug fix
